# Using Python as a Programming Language


We will start with the most important function **help()**

In [0]:
help(str)

## Representig Time

In [0]:
import time

localtime = time.localtime(time.time())
print ("Local current time :", localtime)

Local current time : time.struct_time(tm_year=2019, tm_mon=9, tm_mday=27, tm_hour=1, tm_min=37, tm_sec=6, tm_wday=4, tm_yday=270, tm_isdst=0)


In [0]:
import calendar

cal = calendar.month(2019, 11)
print ("Here is the calendar:")
print (cal)

Here is the calendar:
   November 2019
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



## Representation of Numbers

In [0]:
print(0b11111111,0o377,0xFF,255)

255 255 255 255


## Built-in Math Functions

In [0]:
import math
print( abs(-10), max([1,2,3,4,3,2,1]), min([1,2,3,4,3,2,1]) )
print( math.e, math.pi )
print( math.ceil(12/5), math.floor(12/5), math.exp(1), math.log(math.exp(10)), math.log10(10) )
print( math.pow(2,3), math.sqrt(16) )

10 4 1
2.718281828459045 3.141592653589793
3 2 2.718281828459045 10.0 1.0
8.0 4.0


In [0]:
print(math.sin(0))
print(math.cos(0))
print(math.sin(math.pi))
print(math.cos(math.pi/2))
print(math.sin(math.pi/2))
print(math.cos(math.pi))

0.0
1.0
1.2246467991473532e-16
6.123233995736766e-17
1.0
-1.0


In [0]:
import random
print( random.random() )
print( random.choice([1,2,3,4,5]) )
print( random.randrange (-5,6) )
a = [1,2,3,4,5]
print( random.shuffle(a),a )

0.5124332406178557
1
1
None [2, 3, 1, 4, 5]


## Data Structures: Set, List, Tuple, Dictionary, Matrix and Array

### Set, List, Tuple and Dictionary

In [0]:
A = {1,2,3,5,7}
print(type(A),'\n',len(A))

<class 'set'> 
 5


In [0]:
A = set([1,2,3,4])
print(A)
B = set([3,4,5,6])
print(B)
print(A.union(B))
print(A.intersection(B))
print(A.difference(B))
A.add('a')
print(A)
A.update({1,'b'})
print(A)
A.remove(2)
print(A)
A.remove('a')
print(A)

{1, 2, 3, 4}
{3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{1, 2, 3, 4, 'a'}
{1, 2, 3, 4, 'b', 'a'}
{1, 3, 4, 'b', 'a'}
{1, 3, 4, 'b'}


In [0]:
{x for x in range(-5,5) if x > 0}

{1, 2, 3, 4}

In [0]:
{(x,y) for x in {1,2,3} for y in {'a','b'}}

{(1, 'a'), (1, 'b'), (2, 'a'), (2, 'b'), (3, 'a'), (3, 'b')}

In [0]:
R = {(a,b) for a in {-2,-1,0,1,2} for b in {-2,-1,0,1,2}}
print(R)
R1 = {(a,b) for (a,b) in R if a <= b}
print(R1)
R2 = {(a,b) for (a,b) in R if a > b}
print(R2)
R3 = {(a,b) for (a,b) in R if a == b or a == (-b)}
print(R3)
R4 = {(a,b) for (a,b) in R if a == b}
print(R4)

{(-1, 0), (-2, 0), (2, 1), (0, -1), (1, -2), (1, -1), (1, 2), (-1, 1), (-2, 1), (-1, -1), (-1, -2), (2, 2), (-2, -1), (-2, -2), (1, 1), (0, 0), (2, -1), (2, -2), (-1, 2), (-2, 2), (1, 0), (0, 1), (2, 0), (0, -2), (0, 2)}
{(1, 2), (0, 1), (-1, 1), (-2, 1), (0, 0), (-2, 0), (-1, 0), (2, 2), (-2, -1), (-2, -2), (-1, 2), (-2, 2), (0, 2), (-1, -1), (1, 1)}
{(2, -1), (2, -2), (2, 1), (2, 0), (1, -1), (0, -2), (-1, -2), (0, -1), (1, 0), (1, -2)}
{(-1, 1), (0, 0), (-2, -2), (-1, -1), (2, -2), (-2, 2), (2, 2), (1, -1), (1, 1)}
{(0, 0), (-2, -2), (-1, -1), (2, 2), (1, 1)}


In [0]:
L = [1,2,3,'a','b','c',1,2]
print(L[0])
print(L[-1])
print(L.pop())
print(L.append('x'),L)
print(L.reverse(),L)
print(len(L))
L.insert(0,'A')
L.insert(3,'B')
print(L, len(L))


1
2
2
None [1, 2, 3, 'a', 'b', 'c', 1, 'x']
None ['x', 1, 'c', 'b', 'a', 3, 2, 1]
8
['A', 'x', 1, 'B', 'c', 'b', 'a', 3, 2, 1] 10


In [0]:
L = [8,3,-7,10,6]
print(L.sort(),L)
print(L[:3])
print(max(L))
print(min(L))

None [-7, 3, 6, 8, 10]
[-7, 3, 6]
10
-7


In [0]:
L = ['a','A','b','B','x','X']
print(L.sort(),L)
print(max(L))
print(min(L))

In [0]:
p1 = (1,2,3)
p2 = (4,5,6)
print(p1[0],p2[2])

1 6


In [0]:
# tuple and list
p = (1,2,3,4,5)
q = (4,5,6,7,8)
print(p+q)
print( p[0], p[0:2], p[0:5:2])
p = [1,2,3,4,5]
q = [4,5,6,7,8]
print(p+q)
print( p[0], p[0:2], p[0:5:2])

In [0]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
print(len(fruits))
fruits.append('garlic')
print(fruits)
fruits.count('banana')
fruits.reverse()
print(fruits)
print(fruits.pop())
print(fruits)

In [0]:
A = [1,2,3]
B = [4,5,6]
print(A+B)
A = [[1,2,3],[4,5,6]]
B = [[6,5,4],[3,2,1]]
print(A+B)
print( A[0], A[0:2], A[0][0], A[0][0:2], A[0:2][0] )

In [0]:
a = [1,2,3,4]
print(type(a),a)
b = [ [1],[2],[3],[4]]
print(type(b),b)
c = [ [1,2,3], [4,5,6]]
print(type(c),c)
d = [ [ [1,2,3], [4,5,6] ], [ [1,2,3], [4,5,6] ], [ [1,2,3], [4,5,6] ] ]
print(type(d),d)


<class 'list'> [1, 2, 3, 4]
<class 'list'> [[1], [2], [3], [4]]
<class 'list'> [[1, 2, 3], [4, 5, 6]]
<class 'list'> [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]


In [0]:
# dictionary
D = {}
D['a'] = 1
D['b'] = [1,2,3]
D['c'] = {6,5}
D['e'] = "Hello"
D

In [0]:
D = {'a':'Apple', 'b':'Bat', 'c':3, 4:'April'}
print(D.keys())
print(D.values())
print(D['a'])
print(D.get('a'))
print(type(D))

In [0]:
# dictionary
capital = {'Thailand': 'BKK', 'Malaysia':'KL', 'Brunei':'BWN'}
print(capital['Thailand'])
print('Thailand' in capital)
print('BKK' in capital)
print(*capital)
for c in capital.keys():
  print(capital[c])
for v in capital.values():
  print(v)

BKK
True
False
Thailand Malaysia Brunei
BKK
KL
BWN
BKK
KL
BWN


### A note on list, array and matrix

Python does not have a specific data structure for matrix and array, but a python list may be employed as stack, quque, matrix and array

### Exercises

In [0]:
# write Fibonacci series up to n
def fib(n):    
  """Print a Fibonacci series up to n."""
  a, b = 0, 1
  while a < n:
    print(a, end=' ')
    a, b = b, a+b
  print()
  
fib(100)

0 1 1 2 3 5 8 13 21 34 55 89 


In [0]:
words = ['cat', 'window', 'defenestrate']
for w in words:
  print(w, len(w))

In [0]:
def countWordLength():
  words = input('Type a sentence : ')
  print(words)
  for w in words.split():
    print(w, len(w))
    
countWords()

In [0]:
def countWordFreq():
  words = input('Type a sentence : ')
  print(words)
  D = {}
  for w in words.split():
    if w in D:
      D[w]+= 1
    else:
      D[w] = 1
  print(D)
    
countWordFreq()

Type a sentence : this is this is a test
this is this is a test
{'this': 2, 'is': 2, 'a': 1, 'test': 1}


## Numpy

Numpy is a library for the Python programming language. Numpy adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. 

In [0]:
import numpy as np
a = np.ones(10)
b = np.zeros(10)
print(a,b)
c = np.zeros([2,3])
print(c)
a = np.zeros([2,3])
b = np.ones( [3,2] )
print(a,b)
c = np.ones([10,10],dtype=np.uint8)
print(c)

In [0]:

a = np.array([1,2,3,4])
print(type(a), np.shape(a), a, a[1])

a = np.transpose(np.array([1,2,3,4]))
print(type(a), np.shape(a), a, a[1])

a = np.array([[1,2,3,4]])
print(type(a), np.shape(a), a, a[0])

b = np.array([ [1],[2],[3],[4]])
print(type(b), np.shape(b), b, b[1])

c = np.array([ [1,2,3], [4,5,6]])
print(type(c), np.shape(c), c, c[1])

d = np.array([ [ [1,2,3], [4,5,6] ], [ [1,2,3], [4,5,6] ], [ [1,2,3], [4,5,6] ] ])
print(type(d), np.shape(d), d, d[1])


<class 'numpy.ndarray'> (4,) [1 2 3 4] 2
<class 'numpy.ndarray'> (4,) [1 2 3 4] 2
<class 'numpy.ndarray'> (1, 4) [[1 2 3 4]] [1 2 3 4]
<class 'numpy.ndarray'> (4, 1) [[1]
 [2]
 [3]
 [4]] [2]
<class 'numpy.ndarray'> (2, 3) [[1 2 3]
 [4 5 6]] [4 5 6]
<class 'numpy.ndarray'> (3, 2, 3) [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] [[1 2 3]
 [4 5 6]]


In [0]:
print(np.array([1,2,3]))
print(np.array([1,2,3]).tolist())
print(np.array([1,2,3]).reshape(1,3).tolist())
print(np.array([1,2,3]).reshape(3,1).tolist())
print(np.array([1,2,3]).reshape(1,3,1).tolist())
print(np.array([1,2,3]).reshape(1,3,1,1).tolist())

[1 2 3]
[1, 2, 3]
[[1, 2, 3]]
[[1], [2], [3]]
[[[1], [2], [3]]]
[[[[1]], [[2]], [[3]]]]


In [0]:
p = np.array((1,2,3))
q = np.array((4,5,6))
print(p+q)
print(p*q)
print(p/q)
print(p//q)
print(p%q)
p = np.array([1,2,3])
q = np.array([4,5,6])
print(p+q)
print(p*q)
print(p/q)
print(p//q)
print(p%q)
p = np.array([[1,2,3],[4,5,6]])
q = np.array([[6,5,4],[3,2,1]])
print(p+q)
print(p*q)
print(p/q)
print(p//q)
print(p%q)

In [0]:
A = np.array( [2,3,4,2] )
B = np.array([-1,6,1,3] )
print(np.shape(A),np.shape(B),A*B, B*A)
print(np.shape(np.transpose(A)*B),np.shape(A*np.transpose(B)))
print(np.transpose(A)*B, A*np.transpose(B))

(4,) (4,) [-2 18  4  6] [-2 18  4  6]
(4,) (4,)
[-2 18  4  6] [-2 18  4  6]


In [0]:
# note that this is not matrix multiplication
A = np.array( [[2,3,4,2]] )
B = np.array([[-1],[6],[1],[3]] )
print(np.shape(A),np.shape(B))
print(A*B)
print(B*A)
print(np.shape(np.transpose(A)*B))
print(np.transpose(A)*B)
print(A*np.transpose(B))

(1, 4) (4, 1)
[[-2 -3 -4 -2]
 [12 18 24 12]
 [ 2  3  4  2]
 [ 6  9 12  6]]
[[-2 -3 -4 -2]
 [12 18 24 12]
 [ 2  3  4  2]
 [ 6  9 12  6]]
(4, 1)
[[-2]
 [18]
 [ 4]
 [ 6]]
[[-2 18  4  6]]


In [0]:
A = np.array( [ [ [2,3],[4,2] ], [ [-1,6],[1,3] ], [ [0,-3],[2,4] ] ] )
B = np.array( [ [ [2,3],[4,2] ], [ [-1,6],[1,3] ], [ [0,-3],[2,4] ] ] )
print(np.shape(A))
print(np.shape(np.transpose(A)))
print(np.shape(B))
print(np.shape(np.transpose(B)))

(3, 2, 2)
(2, 2, 3)
(3, 2, 2)
(2, 2, 3)


In [0]:
A = np.matrix( [ [1,3],[0,-3],[2,4] ]  )
B = np.matrix( [ [2,3],[4,2],[-1,6] ]  )
print(np.shape(A))
print(np.shape(np.transpose(A)))
print(np.shape(B))
print(np.shape(np.transpose(B)))

(3, 2)
(2, 3)
(3, 2)
(2, 3)


In [0]:
A = np.array( [ [2,3],[4,2],[-1,6] ] )
B = np.array( [ [1,3],[0,-3],[2,4] ] )
print(np.multiply(A,B))

[[ 2  9]
 [ 0 -6]
 [-2 24]]


In [0]:
A = np.array( [ [ [2,3],[4,2] ], [ [-1,6],[1,3] ], [ [0,-3],[2,4] ] ] )
B = np.array( [ [ [2,3],[4,2] ], [ [-1,6],[1,3] ], [ [0,-3],[2,4] ] ] )
print(np.multiply(A,B))

[[[ 4  9]
  [16  4]]

 [[ 1 36]
  [ 1  9]]

 [[ 0  9]
  [ 4 16]]]


In [0]:
A = np.matrix( [[2,3,4,2]] )
B = np.matrix( [[-1,6,1,3]] )
print(np.transpose(A)*B)
print(A*np.transpose(B))

[[-2 12  2  6]
 [-3 18  3  9]
 [-4 24  4 12]
 [-2 12  2  6]]
[[26]]


In [0]:
A = np.matrix( [ [2,3,4,2], [-1,6,1,3] ])
B = np.matrix( [ [2,3],[4,2],[-1,6],[1,3] ])
print(np.shape(A),np.shape(B))
print(A*B)
print(B*A)

(2, 4) (4, 2)
[[14 42]
 [24 24]]
[[ 1 24 11 13]
 [ 6 24 18 14]
 [-8 33  2 16]
 [-1 21  7 11]]


In [0]:
p = np.array([[1,2,3],[4,5,6]])
q = np.array([[6,5,4],[3,2,1]])
print(np.dot(p,np.transpose(q)))
print(np.dot(np.transpose(p),q))

## Flow Chart, Control Flow and Control Structure

- See https://en.wikipedia.org/wiki/Flowchart
- See https://docs.python.org/3/tutorial/controlflow.html
- Discuss the nature of control ones would expect from writing a computer program

In [0]:
def f1():
  """
  add a lot of comment here
  """
  # add one line coomment here
  x = int(input("Please enter an integer: "))
  if x < 0:
    x = 0
    print('Negative changed to zero')
  elif x == 0:
    print('Zero')
  elif x == 1:
    print('Single')
  else:
    print('Higher than 1')
    
f1()    

Please enter an integer: 56
More


In [0]:
def f2():
  words = ['cat', 'window', 'defenestrate']
  for w in words:
    print(w, len(w), type(w))
    
f2()

cat 3 <class 'str'>
window 6 <class 'str'>
defenestrate 12 <class 'str'>


In [0]:
def f3():
  for num in range(2, 10):
    if num % 2 == 0:
      print("Found an even number", num)
      continue
    print("Found a number", num)
    
f3()

In [0]:
def f4(max):
  for n in range(2, max):
    for x in range(2, n):
      if n % x == 0:
        print(n, 'equals', x, '*', n//x)
        break
    else:
      # loop fell through without finding a factor
      print(n, 'is a prime number')
        
f4(20)

In [0]:
def f5():
  try:
    1/0
  except:
    print( "Divide by zero" )
  finally:
    return 0/1
    
f5()

Divide by zero


0.0

In [0]:
def g1(a, L=[]):
  L.append(a)
  return L

In [0]:
def g2(a, L=None):
  if L is None:
    L = []
  L.append(a)
  return L

In [0]:
def ask_ok(prompt, retries=4, reminder='Please try again!'):
  while True:
    ok = input(prompt)
    if ok in ('y', 'ye', 'yes'):
      return True
    if ok in ('n', 'no', 'nop', 'nope'):
      return False
    retries = retries - 1
    if retries < 0:
      raise ValueError('invalid user response')
    print(reminder)y
    
ask_ok("How is your mum? is she ok?  ")

How is your mum? is she ok?  y


True

In [0]:
adhocask = lambda s : input(s)
adhocask("How is your mum?")

How is your mum?she is ok


'she is ok'

In [0]:
def h1(L):
  for i in L:
    print(f"The item in the list is {i}")
    
h1([1, 23, 456])

The item in the list is 1
The item in the list is 23
The item in the list is 456


In [0]:
def h2(L):
  for n,i in enumerate(L):
    print(f"The item {n} in the list is {i}")
    
h2([1, 23, 456])

The item 0 in the list is 1
The item 1 in the list is 23
The item 2 in the list is 456


In [0]:
def h3(L1,L2):
  for i1,i2 in zip(L1,L2):
    print(f"The item are {i1} and {i2}")
    
h3([1, 23, 456], [123,45,6])

The item are 1 and 123
The item are 23 and 45
The item are 456 and 6


In [0]:
def bubbleSort(arr):
  n = len(arr)
  for i in range(n):
    # Last i elements are already in place
    for j in range(0, n-i-1):
      if arr[j] > arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
  return arr

print(bubbleSort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [0]:
def quickSort(arr):
  if len(arr) <= 1:
    return arr
  pivot = arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]
  return quickSort(left) + middle + quickSort(right)

print(quickSort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


## Object Oriented Programming 

All classes have a function called __init__(), which is always executed when the class is being initiated.

Use the __init__() function to assign values to object properties, or other operations that are necessary to do when the object is being created.

In [0]:
class A:
  var1 = 12
  var2 = 'bars'
  
a1 = A()
a2 = A()
print(a1.var1, a1.var2)
print(a2.var1, a2.var2)
a1.var1 = 'foo'
a1.var2 = 12
print(a1.var1, a1.var2)
print(a2.var1, a2.var2)

12 bars
12 bars
foo 12
12 bars


In [0]:
class B:
  def __init__(self):
    self.var1 = 16
    self.var2 = 'bars'
  
  def boo(self):
    print(self.var1+1,'foo'+self.var2)
  
b1 = B()
print(b1.var1, b1.var2)
b1.boo()

16 bars
17 foobars


In [0]:
class C(B):
  def __init__(self):
    super().__init__()
    self.var3 = 144
    self.var4 = 'bottles'
  
  def boom(self):
    print(self.var3,self.var4)
  
c1 = C()
print(c1.var1, c1.var2)
print(c1.var3, c1.var4)
c1.boo()
c1.boom()

12 bars
144 bottles
13 foobars
144 bottles


In [0]:
class D(A,C):
  def __init__(self):
    super().__init__()
    
d1 = D()
print(d1.var1, d1.var2)
d1.boo()
d1.boom()

12 bars
13 foobars
144 bottles


In [0]:
import math

class Point:
  def __init__(self,x,y):
    self.x = x
    self.y = y
  
  def dist2(self, p):
    return math.sqrt((self.x-p.x)**2 + (self.y-p.y)**2)
  

p1 = Point(1,2)
p2 = Point(3,4)
#p1.dist2(p2)
print( p1.dist2(p2), round(p1.dist2(p2), 3) )

2.8284271247461903 2.828


## Exercises

Try out exercises from  https://www.w3resource.com/python-exercises/




In [0]:
# Write a Python program which adds up columns and rows of given table as shown in the 2D array below
import numpy as np
M = np.array( [[25,69,51,26], [68,35,29,54], [54,57,45,63], [61,68,47,59]] )

def printSumRowsSumCols(M):
  pass

printSumRowsSumCols(M)

In [0]:
# Write a Python program to print the prime number which are less than or equal to a given integer (lower than 100,000).
# For example, execute findLEPrime(10) should retuen [2,3,5,7]

while True:
  try:
    n = int(input('Enter an integer less than 100,000 : '))
    break
  except ValueError:
    print("Oops!  That was no valid number.  Try again...")
if n > 100000:
  print('Your number is more than 100,000, try again...')
else:
  findLEPrime(n)
    
def findLEPrime(n):
  pass

Enter an integer less than 100,000 : 1000000
Your number is more than 100,000, try again...


In [0]:
# Write a Python program to output isolated blobs of binary image below
import numpy as np
I = np.array([[1,1,0,0,0,0,0,1,1,1],[1,0,0,0,0,0,0,1,1,1],[0,0,0,0,0,0,0,1,1,1],
              [0,0,1,0,0,0,0,0,0,0],[0,0,0,0,0,1,1,1,0,0],[0,0,0,0,1,1,1,1,1,0],
              [0,0,0,1,1,1,1,1,1,1],[1,0,0,0,1,1,1,1,1,0],[1,1,0,0,0,1,1,1,0,0],
              [1,1,1,0,0,0,1,0,0,0]])

def countBlobOnes(I):
  pass

countBlobOnes(I)