<a href="https://colab.research.google.com/github/phonamnuaisuk/phonamnuaisuk.github.io/blob/main/Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1: Review

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.6.0'

In [5]:
t = tf.constant(10)
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[1,1],[1,1]])
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [10]:
a = tf.Variable([2., 3.])
b = tf.Variable(a)
a.assign([5., 6.])
print(a.numpy())
print(b.numpy())

[5. 6.]
[2. 3.]


In [17]:
from sklearn.datasets import load_iris
iris = load_iris()

In [18]:
X = iris.data
y = iris.target

In [25]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [24]:
from sklearn.cluster import KMeans
kmodel = KMeans(n_clusters=3)
kmodel.fit(iris.data)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [28]:
import numpy as np
out = kmodel.predict(np.array([[6.6,3.2,5.1,2.1]]))

array([2], dtype=int32)

In [30]:
import tensorflow.keras as keras

## Python skills

In [11]:
Write a bubleSort program https://en.wikipedia.org/wiki/Bubble_sort
<code>
procedure bubbleSort(A : list of sortable items)
    n := length(A)
    repeat
        swapped := false
        for i := 1 to n-1 inclusive do
            /* if this pair is out of order */
            if A[i-1] > A[i] then
                /* swap them and remember something changed */
                swap(A[i-1], A[i])
                swapped := true
            end if
        end for
    until not swapped
end procedure
</code>

In [33]:
def my_bubble_sort1(L):
  n = len(L)
  swapped = True
  while (swapped):
    swapped = False
    for i in range(0,n-1):
      if (L[i] > L[i+1]):
        swapped = True
        temp = L[i+1]
        L[i+1] = L[i]
        L[i] = temp
  return(L)


print(my_bubble_sort1([1,4,2,6,5,3,8,2]))

[1, 2, 2, 3, 4, 5, 6, 8]


# Exercise for week 1

In [ ]:
Write a bubleSort program https://en.wikipedia.org/wiki/Bubble_sort
def bubbleSort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            #if (arr[j] > arr[j+1]):
            #
    return arr

print(bubbleSort([3,6,8,10,1,2,1]))

In [15]:
def my_bubble_sort(L):
  n = len(L)
  for i in range(n):
    for j in range(0,n-i-1):
      if (L[j] > L[j+1]):
        temp = L[j+1]
        L[j+1] = L[j]
        L[j] = temp
  print(L)

my_bubble_sort([10,3,2,5,4,6,9,1])

[1, 2, 3, 4, 5, 6, 9, 10]


In [16]:
Write a quickSort program https://en.wikipedia.org/wiki/Quicksort
def quickSort(arr):
    if len(arr) <= 1:
        return arr
    # your code
    #pivot = arr[0]
    #left = ... element < pivot
    #middle = [pivot]
    #right =  ... element > pivot
    return quickSort(left) + middle + quickSort(right)

print(quickSort([3,6,8,10,1,2,1]))